spring:
  application:
    name: everyhealth

  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URL}
            scope: # google API의 범위 값
              - profile
              - email

  servlet:
    multipart:
      max-file-size: 10MB # 파일당 최대 크기
      max-request-size: 10MB # 요청당 최대 크기

  data:
    redis:
      host: ${REDIS_URL}
      port: 6379

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG


file:
  dir: "C:/coding/spring/project/everyhealth/src/main/resources/images/"

cors:
  allow-url: ${CORS_ALLOW_URL}

jwt:
  secret: ${JWT_SECRET}
  access-token-expire-time: 30 # minutes
  refresh-token-expire-time: 7 # days

server:
  error:
    include-stacktrace: never
    include-message: always