name: Docker CI/CD
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle except for test
        run: ./gradlew build -x test
        env:
          SPRING_PROFILES_ACTIVE: ${{ secrets.DOCKER_SPRING_PROFILES_ACTIVE }}
          GOOGLE_CLIENT: ${{ secrets.GOOGLE_CLIENT }}
          GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          FILE_DIR: ${{ secrets.FILE_DIR }}
          GOOGLE_REDIRECT_URL: ${{ secrets.GOOGLE_REDIRECT_URL }}
          JWT_ACCESS_TOKEN_EXPIRE_TIME: ${{ secrets.JWT_ACCESS_TOKEN_EXPIRE_TIME }}
          JWT_REFRESH_TOKEN_EXPIRE_TIME: ${{ secrets.JWT_REFRESH_TOKEN_EXPIRE_TIME }}

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create env files for Docker
        run: |
          # Backend 환경변수 파일 생성
          cat > .env.backend << EOF
          SPRING_PROFILES_ACTIVE=${{ secrets.DOCKER_SPRING_PROFILES_ACTIVE }}
          GOOGLE_CLIENT=${{ secrets.GOOGLE_CLIENT }}
          GOOGLE_SECRET=${{ secrets.GOOGLE_SECRET }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          FILE_DIR=${{ secrets.FILE_DIR }}
          GOOGLE_REDIRECT_URL=${{ secrets.GOOGLE_REDIRECT_URL }}
          JWT_ACCESS_TOKEN_EXPIRE_TIME=${{ secrets.JWT_ACCESS_TOKEN_EXPIRE_TIME }}
          JWT_REFRESH_TOKEN_EXPIRE_TIME=${{ secrets.JWT_REFRESH_TOKEN_EXPIRE_TIME }}
          EOF

      - name: Build and Push Docker Images
        run: |
          docker compose build
          docker compose push

      - name: Save deployment info
        run: |
          echo "IMAGE_TAG=$(date +%Y%m%d-%H%M%S)" >> deployment-info.txt
          echo "COMMIT_SHA=${{ github.sha }}" >> deployment-info.txt

      - name: Upload deployment artifacts
        uses: actions/upload-artifact@v4
        with:
          name: deployment-info
          path: deployment-info.txt