name: React CI/CD

on:
  push:
    branches:
      - master
    paths:
      - 'src/main/frontend/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Build React app
        run: |
          cd src/main/frontend
          npm ci
          cat > .env << EOF
          REACT_API_BASEURL=${{secrets.REACT_API_BASEURL}}
          REACT_GOOGLE_LOGIN_URL=${{secrets.REACT_GOOGLE_LOGIN_URL}}
          DISABLE_ESLINT_PLUGIN=true
          EOF
          CI=false npm run build

      - name: Upload frontend build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: src/main/frontend/build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: frontend-build

      - name: Debug GitHub Context
        run: |
          echo "GitHub Repository: ${{ github.repository }}"
          echo "GitHub Ref: ${{ github.ref }}"
          echo "GitHub Actor: ${{ github.actor }}"

      - name: Configure AWS credentials with debug
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-s3-cloudfront-role
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GitHubActionsSession
          mask-aws-account-id: false

      - name: Deploy to S3
        run: |
          aws s3 sync frontend-build/ s3://${{ secrets.S3_BUCKET_NAME }} --delete

      - name: Invalidate CloudFront cache
        run: |
          if [ -n "${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}" ]; then
            aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
          else
            echo "CloudFront distribution ID not set, skipping invalidation"
          fi